const Categories = {
    "[Cannon type]": [
        "GM Cannon",
        "Hardygun",
        "Mass Product Gun Cannon",
        "Gun Cannon",
        "Gun Cannon Heavyarmor",
        "Gun Cannon II",
        "Gun Cannon Detector",
        "G Cannon",
        "G Cannon Magna",
        "GM Cannon II",
        "Zaku Cannon",
        "Daughtress Weapon",
        "Cannon Irufuto",
        "GD Cannon"
    ],   
    "[Dom type]": [
        "Rick Dom II",
        "Dom Tropen",
        "Tropical Dom",
        "Dowaji Kai",
        "Pezun Dowaji",
        "Dowaji",
        "Doraizen",
        "Dom Gurosubairu",
        "RF Dom",
        "RF Desert Dom",
        "Dom Bainihitsu"
    ],   
    "[G Gundam type]": [
        "Nobel Gundam",
        "John Bull Gundam",
        "Rising Gundam",
        "Lumber Gundam",
        "Tequilla Gundam",
        "Mermaid Gundam",
        "Nether Gundam",
        "Skull Gundam",
        "Mandala Gundam",
        "Ashura Gundam",
        "Neros Gundam"
    ],   
    "[Gaza type]": [
        "Gaza C",
        "Gaza C Kai",
        "Gaza D",
        "Ga Zoum",
        "Gaza E",
        "Gaza B",
        "Gaza W"
    ],   
    "[Gelgog type]": [
        "Gelgog",
        "Gelgog J",
        "Gelgog M",
        "Desert Gelgog",
        "RF Gelgog",
        "High Mobility Gelgog"
    ],   
    "[Gira Doga type]": [
        "Gira Doga",
        "Gira Doga Kai",
        "Gira Doga Heavyarmor",
        "Gira Doga Psycommu"
    ],   
    "[Gouf type]": [
        "Gouf",
        "Gouf Heavyarmor",
        "Gouf Flight Experiment",
        "B3 Gouf",
        "RF Gouf",
        "Gouf Flight type"
    ],   
    "[Gundam X type]": [
        "Gundam X",
        "Gundam X Divider",
        "Gundam DX",
        "Gundam Airmaster",
        "Gundam Airmaster B",
        "Gundam Leopard",
        "Gundam Leopard Destroy",
        "Gundam Virsago",
        "Gundam Virsago CB",
        "Gundam Ashutaron",
        "Gundam Ashutaron HC",
        "G Falcon",
        "Daughtress",
        "Daughtress Command",
        "DHM Faiawarabi",
        "Daughtress Weapon",
        "Daughtress Tank",
        "Daughtress Neo",
        "Daughtress Furaiya",
        "Doshito",
        "Doshito III",
        "Jenis",
        "Septem",
        "Septem Kai",
        "Okuto Eipu",
        "Okuto Eipu Kai",
        "Jurag",
        "Grantine",
        "Patouria",
        "Federaru"
    ],   
    "[Marine type]": [
        "Aqua GM",
        "Gundiver",
        "Zaku Marine",
        "Higog",
        "Zaku Marina",
        "Gog",
        "Agai",
        "Zugok",
        "Zugok E",
        "Zok",
        "Zogok",
        "Juagu",
        "Agugai",
        "Guraburo",
        "Proba",
        "Kapool",
        "Under Water Experiment Unit",
        "RF Zaku",
        "Zaku Diver",
        "Garugeiyu",
        "RF Zugok",
        "Cancer",
        "Pisces",
        "Mermaid Gundam"
    ],   
    "[Observer type]": [
        "Borinook Samaan",
        "Zaku Flipper",
        "Rugen",
        "Proba",
        "Hover Truck",
        "Aizaku",
        "Dish Comm.",
        "EWAC Nero",
        "Ebil S",
        "Dagi Irus",
        "EWAC Leo",
        "ST Gun",
        "Erebado",
        "Zaku Strong Observer"
    ],   
    "[Gundam W type]": [
        "W Gundam",
        "W Gundam Zero",
        "W Zero Custom",
        "Gundam Deathscythe",
        "Gundam Deathscythe Hell",
        "Gundam Deathscythe Hell Custom",
        "Gundam Heavyarms",
        "Gundam Heavyarms Kai",
        "Gundam Heavyarms Custom",
        "Gundam Sandrock",
        "Gundam Sandrock Kai",
        "Gundam Sandrock Custom",
        "Shenlong Gundam",
        "Altron Gundam",
        "Gundam Nataku"
    ],   
    "[Zanscare type]": [
        "Overhead Hawk",
        "Zoro",
        "Zoro Kai",
        "Tomriat",
        "Zoroat",
        "Shacko",
        "Rig Shacko",
        "Gozora",
        "Memedoza",
        "Abigoru",
        "Garugeiyu",
        "Contioh",
        "Rig Contioh",
        "Shaitan",
        "Gedoraf",
        "Burugengu",
        "Zolidia",
        "Jabako",
        "Domtoria",
        "Zaneck",
        "Dogora",
        "Gengaozo",
        "Gotoratan",
        "Garikuson",
        "Battle Bike Male type",
        "Battle Bike Female type",
        "Rigaru",
        "Birugenau",
        "Rig Ring",
        "Zansupain",
        "Sandoju"
    ],   
    "[Zaku type]": [
        "Zaku II J",
        "Zaku II F",
        "High Mobility Zaku II",
        "Zaku II Kai",
        "Psycommu High Mobility Zaku",
        "Zaku Marine",
        "Zaku Marina",
        "Akuto Zaku",
        "Zaku III",
        "Zaku III Kai",
        "Zaku Flipper",
        "Z Zaku",
        "Zaku Strong Observer",
        "Zaku Minelayer",
        "Zaku 50",
        "Zaku Head",
        "Dizat Zaku",
        "Zaku III Last type",
        "RF Zaku",
        "Zaku Cannon",
        "High Mobility Zaku II",
        "Space use High Mobility Zaku",
        "Bolshanon"
    ],   
    "[Z Gundam type]": [
        "Proto Z Gundam",
        "Mass Product Z Gundam",
        "Z Gundam",
        "Z II",
        "ReGZ",
        "ReGZ Custom",
        "Z Zaku",
        "Z Plus A type",
        "Z Plus C type"
    ],   
};