const TransJA = {
	"Default factory list": "初期生産リスト",

	"Mobile Suit Gundam": "機動戦士ガンダム",
	"Mobile Suit Gundam The 08th MS Team": "機動戦士ガンダム 第08MS小隊",
	"Mobile Suit Gundam Gaiden The Blue Destiny": "機動戦士ガンダム外伝 THE BLUE DESTINY",
	"Mobile Suit Gundam Gaiden Rise of the Ashes": "機動戦士ガンダム外伝 コロニーの落ちた地で",
	"Mobile Suit Gundam 0080 War in the Pocket": "機動戦士ガンダム0080 ポケットの中の戦争",
	"Mobile Suit Gundam 0083 Stardust Memory": "機動戦士ガンダム0083 STARDUST MEMORY",
	"Mobile Suit Z Gundam": "機動戦士Zガンダム",
	"Gundam Sentinel": "GUNDAM SENTINEL",
	"Mobile Suit Gundam ZZ": "機動戦士ガンダムZZ",
	"Mobile Suit Gundam Char's Counterattack": "機動戦士ガンダム 逆襲のシャア",
	"Mobile Suit Gundam Shining Hathaway": "機動戦士ガンダム 閃光のハサウェイ",
	"Mobile Suit Gundam Silhouette Formula 91": "機動戦士ガンダム シルエットフォーミュラ91",
	"Mobile Suit Gundam F91": "機動戦士ガンダムF91",
	"Mobile Suit Crossbone Gundam": "機動戦士クロスボーンガンダム",
	"Mobile Suit V Gundam": "機動戦士Vガンダム",
	"Mobile Fighting Legend G Gundam": "機動武闘伝Gガンダム",
	"New Mobile Report Gundam W": "新機動戦記ガンダムW",
	"New Mobile Century Gundam X": "新機動世紀ガンダムX",

	"[Any Gundam]": "[ガンダム系]",
	"[Any Ball]": "[ボール系]",
	"[Any White Dingo]": "[ホワイトディンゴ隊員]",
	"[Cannon type]": "[キャノン系]",
	"[Dom type]": "[ドム系]",
	"[G Gundam type]": "[Gガンダム系]",
	"[Gaza type]": "[ガザ系]",
	"[Gelgog type]": "[ゲルググ系]",
	"[Gira Doga type]": "[ギラ・ドーガ系]",
	"[Gouf type]": "[グフ系]",
	"[Gundam X type]": "[ガンダムX系]",
	"[Marine type]": "[水中系]",
	"[Observer type]": "[偵察系]",
	"[Gundam W type]": "[ガンダムW系]",
	"[Zanscare type]": "[ザンスカール系]",
	"[Zaku type]": "[ザク系]",
	"[Z Gundam type]": "[Zガンダム系]",

	"Amuro (Z)": "アムロ (Z)",
	"Char (FG)": "シャア (1st)",
	"Noin": "ノイン",
	"Cid": "シド",
	"Gato": "ガトー",
	"Galma": "ガルマ",
	"Gaia": "ガイア",
	"Mashu": "マッシュ",
	"Ortega": "オルテガ",
	"Yazan": "ヤザン",
	"Cima": "シーマ",
	"Dozul": "ドズル",
	"Eniru": "エニル",
	"Jerrid": "ジェリド",
	"Nimbus": "ニンバス",
	"Gavane": "ギャバン",
	"Master": "マスタ",
	"Leon": "レオン",
	"Maximilian": "マクシミリアン",
	"Oderu": "オデル",
	"Lancelot": "ランスロー",
	"Matsunaga": "マツナガ",
	"Anita": "アニタ",
	"Raideen": "ライデン",
	"Ral": "ラル",
	"Chronicle": "クロニクル",
	"Marbet": "マーベット",

	"Aizaku": "アイザック",
	"Aqua GM": "アクアジム",
	"Akushirio": "アクリシオ",
	"Akuto Zaku": "アクトザク",
	"Ashura Gundam": "アシュラガンダム",
	"Agai": "アッガイ",
	"Agu": "アッグ",
	"Agugai": "アッグガイ",
	"Azam": "アッザム",
	"Azam (grey)": "アッザム（灰）",
	"Ashima": "アッシマー",
	"Ashima": "アッシマー",
	"Abigoru": "アビゴル",
	"Abigoru": "アビゴル",
	"Abijo": "アビジョ",
	"Apsalas II": "アプサラス II",
	"Apsalas III": "アプサラス III",
	"Amuro's Custom Waverider A type": "アムロ専用ウェイブライダーA型",
	"Amuro's Custom Z Plus A type": "アムロ専用ZプラスA型",
	"RX-81 Standard": "RX-81スタンダード",
	"RX-81 Lightarmor": "RX-81ライトアーマー",
	"R Jaja": "R・ジャジャ",
	"Altron Gundam": "アルトロンガンダム",
	"Alpha Aziel": "アルパ・アジール",
	"Ex-S Gundam": "EX-Sガンダム",
	"Iguru": "イーゲル",
	"Ez8": "Ez8",
	"Ez8 HMC": "Ez8 HMC",
	"Ez8 HAC": "Ez8 HAC",
	"Ifrit": "イフリート",
	"Ifrit Kai": "イフリート改",
	"EWAC Nero": "EWACネロ",
	"EWAC Leo": "EWACリーオー",
	"Vayeat": "ヴァイエイト",
	"Vayeat Shuivan": "ヴァイエイト・シュイヴァン",
	"Vagon": "ヴァゴン",
	"Wad": "ウァッド",
	"Val Valo": "ヴァル・ヴァロ",
	"V Gundam": "Vガンダム",
	"V Gundam (MS)": "Vガンダム（MS形態）",
	"V Gundam (Split)": "Vガンダム（分離形態）",
	"V Gundam Hexa": "Vガンダム・ヘキサ",
	"V Gundam Hexa (MS)": "Vガンダム・ヘキサ（MS形態）",
	"V Gundam Hexa (Split)": "Vガンダム・ヘキサ（分離形態）",
	"V Dash Gundam (MS)": "Vダッシュ・ガンダム（MS形態）",
	"V Dash Gundam (Split)": "Vダッシュ・ガンダム（分離形態）",
	"V2 Assault": "V2アサルト",
	"V2 Assault Buster": "V2アサルトバスター",
	"V2 Gundam": "V2ガンダム",
	"V2 Buster": "V2バスター",
	"W Gundam": "Wガンダム",
	"W Gundam (Bird Mode)": "Wガンダム（バード形態）",
	"W Gundam Zero": "Wガンダムゼロ",
	"W Gundam Zero (Bird Mode)": "Wガンダムゼロ（バード形態）",
	"W Zero Custom": "Wゼロカスタム",
	"Waverider": "ウェイブライダー",
	"Waverider A type": "ウェイブライダーA型",
	"Waverider C type": "ウェイブライダーC型",
	"Wudom": "ウォドム",
	"Walter Gundam": "ウォルターガンダム",
	"Space use High Mobility Zaku": "宇宙用高機動試験型ザク",
	"Aries": "エアリーズ",
	"Aries (Federation MS)": "エアリーズ（連合仕様・MS形態）",
	"Aries (Federation MA)": "エアリーズ（連合仕様・MA形態）",
	"Aries (MS)": "エアリーズ（MS形態）",
	"Aries (MA)": "エアリーズ（MA形態）",
	"Aries (Noin MS)": "エアリーズ（ノイン機・MS形態）",
	"Aries (Noin MA)": "エアリーズ（ノイン機・MA形態）",
	"Estarudosu": "エスタルドス",
	"ST Gun": "STガン",
	"Esperansa": "エスペランサ",
	"Ebil S": "エビル・S",
	"Ebil S (Black)": "エビル・S（黒）",
	"Ebil Doga": "エビル・ドーガ",
	"Elmeth": "エルメス",
	"Eregorera": "エレゴレラ",
	"Erebado": "エレバド",
	"Erefante": "エレファンテ",
	"Oasis": "オアシス",
	"Okuto Eipu": "オクト・エイプ",
	"Okuto Eipu Kai": "オクト・エイプ改",
	"Overhead Hawk": "オーバーヘッドホーク",
	"Oriphant": "オリファント",
	"Gaia's Custom High Mobility Zaku II": "ガイア専用高機動ザクII",
	"Gaia's Custom Zaku I": "ガイア専用ザクI",
	"Gaza B": "ガザB",
	"Gaza C": "ガザC",
	"Gaza C Kai": "ガザC改",
	"Gaza D": "ガザD",
	"Gaza E": "ガザE",
	"Gaza W": "ガザW",
	"Gaza R": "ガズアル",
	"Gaza L": "ガズエル",
	"Ga Zoum": "ガ・ゾウム",
	"Gasha": "ガッシャ",
	"Gadiru": "ガディール",
	"Gato's Custom Gelgog": "ガトー専用ゲルググ",
	"Gatoru": "ガトル",
	"Gabusurei": "ガブスレイ",
	"Kaburu": "カプル",
	"Kapool": "カプール",
	"Kashingu": "カッシング",
	"Gaburu": "ガプル",
	"Gabera Tetra": "ガーベラ・テトラ",
	"Garikuson": "ガリクソン",
	"Garugeiyu": "ガルグイユ",
	"Garugeiyu (MS)": "ガルグイユ（MS形態）",
	"Garugeiyu (MA)": "ガルグイユ（MA形態）",
	"Garusu J": "ガルスJ",
	"Galbady a": "ガルバルディa",
	"Galbady B": "ガルバルディB",
	"Galma's Custom Zaku II": "ガルマ専用ザクII",
	"Galma's Custom Dop": "ガルマ専用ドップ",
	"GunEZ": "ガンイージ",
	"Gun Cannon": "ガンキャノン",
	"Gun Cannon II": "ガンキャノン II",
	"Gun Cannon Heavyarmor": "ガンキャノン重装型",
	"Gun Cannon Detector": "ガンキャノン・ディクテイター",
	"Kangurijo": "カングリジョ",
	"Gundiver": "ガンダイバー",
	"Gundam": "ガンダム",
	"Gundam (Headless)": "ガンダム（半壊）",
	"Gundam Akueriasu": "ガンダムアクエリアス",
	"Gundam Ashutaron": "ガンダムアシュタロン",
	"Gundam Ashutaron (No Equipment)": "ガンダムアシュタロン（装備無し）",
	"Gundam Ashutaron HC": "ガンダムアシュタロンHC",
	"Gundam Asukureopuosu": "ガンダムアスクレオプス",
	"Gundam Virsago": "ガンダムヴァサーゴ",
	"Gundam Virsago CB": "ガンダムヴァサーゴ・CB",
	"Gundam Airmaster": "ガンダムエアマスター",
	"Gundam Airmaster B": "ガンダムエアマスター・B",
	"Gundam X": "ガンダムX",
	"Gundam X Divider": "ガンダムXディバイダー",
	"Gundam NT1": "ガンダムNT1",
	"Gundam NT1-FA": "ガンダムNT1-FA",
	"Gundam Epyon": "ガンダムエピオン",
	"Gundam F90": "ガンダムF90",
	"Gundam F90 (Unit 2)": "ガンダムF90（2号機）",
	"Gundam F90 (Unit 2 Red)": "ガンダムF90（2号機・赤）",
	"Gundam F90 A": "ガンダムF90A",
	"Gundam F90 M": "ガンダムF90M",
	"Gundam F90 S": "ガンダムF90S",
	"Gundam F90 II": "ガンダムF90II",
	"Gundam F90 II I": "ガンダムF90II I",
	"Gundam F90 II L": "ガンダムF90IIL",
	"Gundam F91": "ガンダムF91",
	"Gundam LO Booster": "ガンダムLOブースター",
	"Gundam Grip": "ガンダムグリープ",
	"Gundam Sandrock": "ガンダムサンドロック",
	"Gundam Sandrock Kai": "ガンダムサンドロック改",
	"Gundam Sandrock Custom": "ガンダムサンドロックカスタム",
	"Gundam Geminas 01": "ガンダムジェミナス01",
	"Gundam Geminas 02": "ガンダムジェミナス02",
	"Gundam Spiegel": "ガンダムシュピーゲル",
	"Gundam DX": "ガンダムDX",
	"Gundam Deathscythe": "ガンダムデスサイズ",
	"Gundam Deathscythe Hell": "ガンダムデスサイズヘル",
	"Gundam Deathscythe Hell Custom": "ガンダムデスサイズヘルカスタム",
	"Gundam Nataku": "ガンダムナタク",
	"Gundam Banrepuosu": "ガンダムバーンレプオス",
	"Gundam Pixy": "ガンダムピクシー",
	"Gundam Head": "ガンダムヘッド",
	"Gundam Heavyarms": "ガンダムヘビーアームズ",
	"Gundam Heavyarms Kai": "ガンダムヘビーアームズ改",
	"Gundam Heavyarms Custom": "ガンダムヘビーアームズカスタム",
	"Gundam Heavens Sword": "ガンダムヘブンズソード",
	"Gundam Berufegoru": "ガンダム・ベルヘゴール",
	"Gundam Mk II": "ガンダムMKII",
	"Gundam Mk II (AEUG)": "ガンダムMKII（エゥーゴ）",
	"Gundam Mk II (Titans)": "ガンダムMKII（ティターンズ）",
	"Gundam Mk III": "ガンダムMKIII",
	"Gundam Mk IV": "ガンダムMKIV",
	"Gundam Mk V": "ガンダムMKV",
	"Gundam Maxter": "ガンダムマックスター",
	"Gundam MA Mode": "ガンダムMAモード",
	"Gundam Leopard": "ガンダムレオパルド",
	"Gundam Leopard (Under Water)": "ガンダムレオパルド（水中用）",
	"Gundam Leopard Destroy": "ガンダムレオパルド・デストロイ",
	"Gundam Rose": "ガンダムローズ",
	"Guntank": "ガンタンク",
	"Guntank II": "ガンタンクII",
	"Guntank R44": "ガンタンクR44",
	"Gunblastor": "ガンブラスター",
	"Cold Land use GM": "寒冷地専用ジム",
	"Gigan": "ギガン",
	"Gigantic": "ギガンティック",
	"Kikeroga": "キケロガ",
	"Casval's Custom Gundam": "キャスバル専用ガンダム",
	"Kyatoru": "キャトル",
	"Cannon Irufuto": "キャノン・イルフート",
	"Gavane's Custom Bolshanon": "ギャバン専用ボルジャーノン",
	"Gyaburan": "ギャプラン",
	"Gyaburan Kai": "ギャプラン改",
	"Gyan": "ギャン",
	"Gyan Kai": "ギャン改",
	"Cancer": "キャンサー",
	"Gyan Mass Product": "ギャン量産型",
	"Qubeley": "キュベレイ",
	"Qubeley (Puru)": "キュベレイ（プル）",
	"Qubeley (Puru Two)": "キュベレイ（プルツー）",
	"Qubeley Mk II": "キュベレイMkII",
	"Qubeley Mk II (Puru)": "キュベレイMkII（プル）",
	"Qubeley Mk II (Puru Two)": "キュベレイMkII（プルツー）",
	"Gira Doga": "ギラ・ドーガ",
	"Gira Doga (Leader type)": "ギラ・ドーガ（指揮官機）",
	"Gira Doga Kai": "ギラ・ドーガ改",
	"Gira Doga Psycommu": "ギラ・ドーガサイコミュ試験型",
	"Gira Doga Heavyarmor": "ギラ・ドーガ重装型",
	"Guabaze": "クァバーゼ",
	"Queen Mantha": "クィン・マンサ",
	"Queen Mantha (Head)": "クィン・マンサ（ヘッド）",
	"Qell Doga": "クェル・ドーガ",
	"Guza": "グザ",
	"I (Kusi) Gundam": "クスィーガンダム",
	"Gustaf Karu": "グスタフ・カール",
	"Gouf": "グフ",
	"Gouf Heavyarmor": "グフ重装型",
	"Gouf Flight Experiment": "グフ飛行試験型",
	"Gouf Flight type": "グフフライトタイプ",
	"Kurauda": "クラウダ",
	"Cluster Gundam": "クラスターガンダム",
	"Guraburo": "グラブロ",
	"Granzam": "グランザム",
	"Grantine": "グランディーネ",
	"Grand Gundam": "グランドガンダム",
	"Grand Master Gundam": "グランドマスターガンダム",
	"3 Black Star's Custom Zaku I": "黒い三連星専用ザクI",
	"3 Black Star's Custom High Mobility Zaku II": "黒い三連星専用機動型ザクII",
	"Crossbone Gundam X1": "クロスボーン・ガンダムX1",
	"Crossbone Gundam X1 Kai": "クロスボーン・ガンダムX1改",
	"Crossbone Gundam X2": "クロスボーン・ガンダムX2",
	"Crossbone Gundam X2 Kai": "クロスボーン・ガンダムX2改",
	"Crossbone Gundam X3": "クロスボーン・ガンダムX3",
	"Guromurin": "グロムリン",
	"Kowloon Gundam": "クーロンガンダム",
	"Geze": "ゲゼ",
	"Geze (Gemon)": "ゲゼ（ゲモン）",
	"Geze (Yazan)": "ゲゼ（ヤザン）",
	"Gedoraf": "ゲドラフ",
	"Gedoraf (Twin Rad)": "ゲドラフ（ツインラッド）",
	"Gemaruku": "ゲーマルク",
	"Gelgog": "ゲルググ",
	"Gelgog (Leader type)": "ゲルググ（指揮官機）",
	"Gelgog J": "ゲルググJ",
	"Gelgog M": "ゲルググM",
	"Gelgog Cannon": "ゲルググキャノン",
	"Gengaozo": "ゲンガオゾ",
	"Kempher": "ケンプファー",
	"Core Easy": "コア・イージー",
	"Core Fighter": "コア・ファイター",
	"Core Fighter (G-3)": "コア・ファイター（G-3）",
	"Core Fighter (V2)": "コア・ファイター（V2）",
	"Core Fighter (V2AB)": "コア・ファイター（V2AB）",
	"Core Fighter (X1)": "コア・ファイター（X1）",
	"Core Fighter (X2)": "コア・ファイター（X2）",
	"Core Fighter (X3)": "コア・ファイター（X3）",
	"Core Fighter ZZ": "コア・ファイターZZ",
	"Core Fighter (Cluster)": "コア・ファイター（クラスター）",
	"Core Fighter (Turn A)": "コア・ファイター（ターンエー）",
	"Core Fighter (Neo)": "コア・ファイター（ネオ）",
	"Core Fighter (Casval type)": "コア・ファイター（キャスバル専用）",
	"Core Fighter II": "コア・ファイターII",
	"Core Fighter II-Fb": "コア・ファイターII-FB",
	"Core Fighter V": "コア・ファイターV",
	"Core Booster": "コア・ブースター",
	"High Mobility Gelgog": "高機動型ゲルググ",
	"High Mobility Gelgog (Leader type)": "高機動型ゲルググ（指揮官機）",
	"High Mobility Zaku II": "高機動型ザクII",
	"High Mobility Zaku II (Leader type)": "高機動型ザクII（指揮官機）",
	"High Mobility Operation Unit": "高機動試作機",
	"High Mobility Leo": "高機動型リーオー",
	"Gog": "ゴッグ",
	"Gog (Black)": "ゴッグ（黒）",
	"Gozo": "ゴッゾー",
	"Gozora": "ゴッゾーラ",
	"God Gundam": "ゴッドガンダム",
	"Gotoratan": "ゴトラタン",
	"Korureru": "コルレル",
	"Contioh": "コンティオ",
	"Psyco Gundam": "サイコガンダム",
	"Psyco Gundam Mk II": "サイコガンダムMKII",
	"Psyco Gundam Mk II (Head)": "サイコガンダムMKII（ヘッド）",
	"Psyco Gundam Mk III": "サイコガンダムMKIII",
	"Psyco Doga": "サイコ・ドーガ",
	"Psyco Halo": "サイコ・ハロ",
	"Psycommu High Mobility Zaku": "サイコミュ高機動試験用ザク",
	"Psycommu Zaku": "サイコミュ試験用ザク",
	"Psycoro Gundam": "サイコロガンダム",
	"Zaku I": "ザクI",
	"Zaku I (Top)": "ザクI（トップ）",
	"Zaku II F": "ザクIIF型",
	"Zaku II F (Leader type)": "ザクIIF型（指揮官機）",
	"Zaku II F (Desert Color)": "ザクIIF型（デザートカラー）",
	"Zaku II J": "ザクIIJ型",
	"Zaku II J (Leader type)": "ザクIIJ型（指揮官機）",
	"Zaku II J (White)": "ザクIIJ型（白）",
	"Zaku II J (Asu)": "ザクIIJ型（アス機）",
	"Zaku II J (Deru)": "ザクIIJ型（デル機）",
	"Zaku II J (Kimbarait)": "ザクIIJ型（キンバライト）",
	"Zaku II J (Kimbarait Brown)": "ザクIIJ型（キンバライト茶）",
	"Zaku II Kai": "ザクII改",
	"Zaku II Kai (Leader type)": "ザクII改（指揮官機）",
	"Zaku III": "ザクIII",
	"Zaku III Kai": "ザクIII改",
	"Zaku III Last type": "ザクIII後期型",
	"Zaku 50": "ザク50",
	"Zaku Cannon": "ザクキャノン",
	"Zaku Cannon (Leader type)": "ザクキャノン（指揮官機）",
	"Zaku Strong Observer": "ザク強行偵察型",
	"Zaku Speed": "ザク・スピード",
	"Zaku Diver": "ザクダイバー",
	"Zakutank": "ザクタンク",
	"Zaku Flipper": "ザクフリッパー",
	"Zaku Head": "ザクヘッド",
	"Zaku Minelayer": "ザクマインレイヤー",
	"Zaku Marina": "ザクマリナー",
	"Zaku Marina (Leader type)": "ザクマリナー（指揮官機）",
	"Zaku Marine": "ザクマリン",
	"Zakurelo": "ザクレロ",
	"Sazabi": "サザビー",
	"Zani": "ザニー",
	"Serpent": "サーペント",
	"Zameru": "ザメル",
	"Zansupain": "ザンスパイン",
	"Sandoju": "サンドージュ",
	"Zaneck": "ザンネック",
	"Jegan": "ジェガン",
	"Jegan A type": "ジェガンAタイプ",
	"Jegan B type": "ジェガンBタイプ",
	"Jegan Kai": "ジェガン改",
	"Jegan Heavyarmor": "ジェガン重装型",
	"GX Bit": "GXビット",
	"Jetstream": "ジェットストリーム",
	"Jenis": "ジェニス",
	"Jenis Kai": "ジェニス改",
	"Jenis Kai (Eniru Custom)": "ジェニス改（エニルカスタム）",
	"Jenis Kai (Kuroka Original)":  "ジェニス改（クロッカオリジナル）",
	"Jenis Kai (Slash Baffalo)": "ジェニス改（スラッシュバッファロー）",
	"Jemzugan": "ジェムズガン",
	"Shenlong Gundam": "シェンロンガンガム",
	"The O": "ジ・O",
	"Ziong": "ジオング",
	"Ziong (Head)": "ジオング（ヘッド）",
	"G Cannon": "Gキャノン",
	"G Cannon Magna": "Gキャノンマグナ",
	"G Cruiser": "Gクルーザー",
	"G Core": "Gコア",
	"G-3 Gundam": "G-3ガンダム",
	"GW Bit": "GWビット",
	"Jiko": "ジッコ",
	"GT Bit": "GTビット",
	"G Defensor": "Gディフェンサー",
	"GT Four": "GT-FOUR",
	"GT Four (G mode)": "GT-FOUR（Gモード）",
	"GT Four (B mode)": "GT-FOUR（Bモード）",
	"GD Cannon": "GDキャノン",
	"GD Striker": "GDストライカー",
	"Cid's Custom Gira Doga Kai": "シド専用ギラ・ドーガ改",
	"GP01": "GP01",
	"GP01-Fb": "GP01-FB",
	"GP02": "GP02",
	"GP02A": "GP02A",
	"GP03-D": "GP03-D",
	"GP03-S": "GP03-S",
	"GP04G": "GP04G",
	"G Fighter": "Gファイター",
	"G Falcon": "Gファルコン",
	"G Falcon GX": "GファルコンGX",
	"G Falcon Airmaster": "Gファルコンエアマスター",
	"G Falcon DX": "GファルコンDX",
	"G Falcon Destroy": "Gファルコンデストロイ",
	"G Falcon Burst": "Gファルコンバースト",
	"G Falcon Leopard": "Gファルコンレオパルド",
	"G Fortress": "Gフォートレス",
	"G Fortress O": "Gフォートレス0型",
	"Cima's Custom Gelgog M": "シーマ専用ゲルググM",
	"GM": "ジム",
	"GM (Grey)": "ジム（灰）",
	"GM II": "ジムII",
	"GM II (Federation)": "ジムII（連邦仕様）",
	"GM II (AEUG)": "ジムII（エゥーゴ仕様）",
	"GM III": "ジムIII",
	"GM III (Federation)": "ジムIII（連邦仕様）",
	"GM III (AEUG)": "ジムIII（エゥーゴ仕様）",
	"GM Kai": "ジム改",
	"GM Kai (Desert Color)": "ジム改（デザートカラー）",
	"GM Custom": "ジム・カスタム",
	"GM Custom (Burning)": "ジム・カスタム（バニング機）",
	"GM Custom High Mobility type": "ジム・カスタム高機動型",
	"GM Cannon": "ジムキャノン",
	"GM Cannon (Grey)": "ジムキャノン（灰）",
	"GM Cannon II": "ジム・キャノンII",
	"GM Quail": "ジム・クゥエル",
	"GM Commando": "ジムコマンド",
	"GM Sniper": "GMスナイパー",
	"GM Sniper Custom": "ジムスナイパーカスタム",
	"GM Sniper II": "ジムスナイパーII",
	"GM Trainer": "ジムトレーナー",
	"GM Head": "ジムヘッド",
	"GM Lightarmor": "ジムライトアーマー",
	"Char's Custom Gelgog": "シャア専用ゲルググ",
	"Char's Custom Zaku II": "シャア専用ザクII",
	"Char's Custom Zugok": "シャア専用ズゴック",
	"Char's Custom Rick Dom": "シャア専用リック・ドム",
	"Shaitan": "シャイターン",
	"Shining Gundam": "シャイニングガンダム",
	"Shacko": "シャッコー",
	"Shuffle Club": "シャッフル・クラブ",
	"Shuffle Joker": "シャッフル・ジョーカー",
	"Shuffle Spade": "シャッフル・スペード",
	"Shuffle Dia": "シャッフル・ダイヤ",
	"Shuffle Heart": "シャッフル・ハート",
	"Jabako": "ジャバコ",
	"Javelin": "ジャベリン",
	"Jamal Fin": "ジャムル・フィン",
	"Juagu": "ジュアッグ",
	"Shutsurum Dias": "シュツルム・ディアス",
	"Jurag": "ジュラッグ",
	"John Bull Gundam": "ジョンブルガンダム",
	"Shilhouette Gundam": "シルエットガンダム",
	"Shilhouette Gundam Kai": "シルエットガンダム改",
	"Under Water Experiment Unit": "水中実験機",
	"Skull Gundam": "スカルガンダム",
	"Zugok": "ズゴック",
	"Zugok E": "ズゴックE",
	"Scorpio": "スコーピオ",
	"Zusa": "ズサ",
	"Zusa Custom": "ズサカスタム",
	"Zusa Dain": "ズサ・ダイン",
	"Zusan": "ズサン",
	"Stark Jegan": "スターク・ジェガン",
	"Super Gundam": "スーパーガンダム",
	"S Gundam": "Sガンダム",
	"S Gundam (Split)": "Sガンダム（分離形態）",
	"S Gundam (Booster)": "Sガンダム（ブースター）",
	"Sumo": "スモー",
	"Seiba Fish": "セイバーフィッシュ",
	"Seiba Fish (Leader type)": "セイバーフィッシュ（指揮官機）",
	"Top Fighter V": "トップ・ファイターV",
	"Top Fighter V (Hexa)": "トップ・ファイター（ヘキサ）",
	"Top Fighter V2": "トップ・ファイターV2",
	"Top Terminal": "トップターミナル",
	"Top Terminal (Red)": "トップターミナル（赤）",
	"Zeg Ain": "セグ・アイン",
	"Zeg Tsuvai": "セグ・ツヴァイ",
	"Z Gundam": "Zガンダム",
	"Z Gundam (Wave Rider)": "Zガンダム（ウェイブライダー）",
	"Z Zaku": "Zザク",
	"Z Plus A type": "ZプラスA型",
	"Z Plus C type": "ZプラスC型",
	"Z II": "Z II",
	"Septem": "セプテム",
	"Septem Kai": "セプテム改",
	"Septem Kai (Red)": "セプテム改（赤）",
	"First Ball": "先行量産型ボール",
	"Battle Bike Male type": "戦斗バイク甲タイプ",
	"Battle Bike Female type": "戦斗バイク乙タイプ",
	"Battle Helicopter": "戦闘ヘリコプター",
	"Zoan": "ゾアン",
	"Armored Car": "装甲車",
	"Zogok": "ゾゴック",
	"Zok": "ゾック",
	"Zodi Ack": "ゾディ・アック",
	"Zodi Ack Mass Product": "ゾディ・アック量産型",
	"Zolidia": "ゾリディア",
	"Zoro": "ゾロ",
	"Zoro (Split)": "ゾロ（分離形態）",
	"Zoro (Red)": "ゾロ（赤）",
	"Zoro (Red Split)": "ゾロ（赤・分離形態）",
	"Zoroat": "ゾロアット",
	"Zoroat (White)": "ゾロアット（白）",
	"Zoroat (Atmospheric Reentry capable)": "ゾロアット（大気圏内活動可能）",
	"Zoro Kai": "ゾロ改",
	"Zondo Ge": "ゾンド・ゲー",
	"Titania": "タイタニア",
	"Dagi Irus": "ダギ・イルス",
	"Dagi Irus (White)": "ザギ・イルス（白）",
	"ZZ Gundam": "ZZガンダム",
	"ZZ Gundam (G-fortress)": "ZZガンダム（Gフォートレス）",
	"ZZ Gundam-FA": "ZZガンダム-FA",
	"D Gundam First": "Dガンダムファースト",
	"D Gundam Second": "Dガンダムセカンド",
	"D Gundam Third": "Dガンダムサード",
	"Turn A Gundam": "ターンエーガンダム",
	"Turn X": "ターンX",
	"Diona": "ディオナ",
	"Desert Zaku": "ディザート・ザク",
	"Dije": "ディジェ",
	"Dije SE-R": "ディジェSE-R",
	"Dish Comm.": "ディッシュ連絡機",
	"Dibinidado": "ディビニダド",
	"D Unit": "Dユニット",
	"TIN Cod": "TINコッド",
	"Tequilla Gundam": "テキーラガンダム",
	"Desert Gelgog": "デザートゲルググ",
	"Desert GM": "デザートジム",
	"Death Army": "デスアーミー",
	"Death Navy": "デスネイビー",
	"Death Bat": "デスバッド",
	"Death Body": "デスバーディ",
	"Death Beast": "デスビースト",
	"Denon Ge": "デナン・ゲー",
	"Denon Ge (Black)": "デナン・ゲー（黒）",
	"Denon Zon": "デナン・ゾン",
	"Denon Zon (Black)": "デナン・ゾン（黒）",
	"Devil Gundam": "デビルガンダム",
	"Devil Gundam (Final)": "デビルガンダム（最終形態）",
	"Devil Gundam Jr.": "デビルガンダムJR",
	"Dep Rog": "デプ・ロッグ",
	"Doga": "ドーガ",
	"Doshito": "ドーシート",
	"Doshito III": "ドーシートIII",
	"Dozul's Custom Zaku II": "ドズル専用ザクII",
	"Dotapu": "ドータップ",
	"Dotapu Under Water type": "ドータップ水中型",
	"Dogora": "ドッゴーラ",
	"Dogora (Blue)": "ドッゴーラ（青）",
	"Dogora (Red)": "ドッゴーラ（赤）",
	"Dop": "ドップ",
	"Totoga": "トトゥガ",
	"Daughtress": "ドートレス",
	"Daughtress (Federation)": "ドートレス（連邦）",
	"Daughtress (Alternative)": "ドートレス（アルタネイティブ）",
	"Daughtress Weapon": "ドートレス・ウェポン",
	"Daughtress Weapon (Federation)": "ドートレス・ウェポン（連邦）",
	"Daughtress Weapon (Alternative)": "ドートレス・ウェポン（アルタ）",
	"Daughtress Kai": "ドートレス改",
	"Daughtress Command": "ドートレス・コマンド",
	"Daughtress Command (Federation)": "ドートレス・コマンド（連邦）",
	"Daughtress Command (Alternative)": "ドートレス・コマンド（アルタ	）",
	"Daughtress Tank": "ドートレスタンク",
	"Daughtress Neo": "ドートレス・ネオ",
	"DHMC Waizuwarabi": "DHMCワイズワラビー",
	"DHM Faiawarabi": "DHMファイヤーワラビー",
	"Daughtress Furaiya": "ドートレスフライヤー",
	"Dobenwolf": "ドーベンウルフ",
	"Dom": "ドム",
	"Dom Gurosubairu": "ドム・グロウスバイル",
	"Domtoria": "ドムットリア",
	"Domtoria (MS)": "ドムットリア（MS形態）",
	"Domtoria (MA)": "ドムットリア（MA形態）",
	"Dom Tropen": "ドム・トローペン",
	"Dom Tropen (Kimbarait)": "ドム・トローペン（キンバライト）",
	"Dom Bainihitsu": "ドム・バインニヒツ",
	"D.O.M.E. Bit": "D.O.M.E.ビット",
	"Tomriat": "トムリアット",
	"Tomriat (MS)": "トムリアット（MS形態）",
	"Tomriat (MA)": "トムリアット（MA形態）",
	"Doraizen": "ドライセン",
	"Toragos": "トラゴス",
	"Dragon Gundam": "ドラゴンガンダム",
	"Dragon Fly": "ドラゴン・フライ",
	"Taurus": "トーラス",
	"Taurus (Red)": "トーラス（赤）",
	"Taurus (White)": "トーラス（白）",
	"Doratsue": "ドラッツェ",
	"Toria Ace FF-4": "トリアーエズFF-4",
	"Tallgeese": "トールギス",
	"Tallgeese II": "トールギスII",
	"Tallgeese III": "トールギスIII",
	"Tornado Gundam": "トルネードガンダム",
	"Tropical Dom": "トロピカルドム",
	"Dowaji": "ドワッジ",
	"Dowaji Kai": "ドワッジ改",
	"Don Escargo": "ドン・エスカルゴ",
	"Nightingale": "ナイチンゲール",
	"Knight Gundam": "ナイトガンダム",
	"Nu Gundam": "ニューガンダム",
	"Nu Gundam HWS": "ニューガンダムHWS",
	"NT Operation GM Jagura": "NT試験用ジム・ジャグラー",
	"Nubel GM III": "ヌーベルジムIII",
	"Neo Gundam": "ネオガンダム",
	"Neo Gundam (Unit 1)": "ネオガンダム（1号機）",
	"Neo Gundam (Unit 2)": "ネオガンダム（2号機）",
	"Nether Gundam": "ネーデルガンダム",
	"Nemo": "ネモ",
	"Nemo III": "ネモIII",
	"Nero": "ネロ",
	"Neros Gundam": "ネロスガンダム",
	"Nero Trainer": "ネロ・トレーナー",
	"Noie Ziel": "ノイエ・ジール",
	"Noie Ziel II": "ノイエ・ジールII",
	"Nautilus": "ノーティラス",
	"Nobushi": "ノブッシ",
	"Nobel Gundam": "ノーベルガンダム",
	"Baiaran": "バイアラン",
	"Higog": "ハイ・ゴッグ",
	"Hizaku": "ハイザック",
	"Hizaku (Titans)": "ハイザック（ティターンズ仕様）",
	"Hizaku (Federation)": "ハイザック（連邦仕様）",
	"Hizaku Custom": "ハイザックカスタム",
	"Pisces": "パイシーズ",
	"Pisces (MS)": "パイシーズ（MS形態）",
	"Pisces (MA)": "パイシーズ（MA形態）",
	"Hydra Gundam": "ハイドラガンダム",
	"Hi Nu Gundam": "HIニューガンダム",
	"Bairon": "パイロン",
	"Bairon Kai": "パイロン改",
	"Bau": "バウ",
	"Bau (MS)": "バウ (MS形態)",
	"Bau (MA)": "バウ（MA形態）",
	"Bau (Green MS)": "バウ（緑・MS形態）",
	"Bau (Green MA)": "バウ（緑・MA形態）",
	"Bau Attacker": "バウアタッカー",
	"Bau Attacker (Green)": "バウアタッカー（緑）",
	"Bound Dog": "バウンド・ドッグ",
	"Bound Dog (MS Grey)": "バウンド・ドック（MS形態・灰）",
	"Bound Dog (MA Grey)": "バウンド・ドック（MA形態・灰）",
	"Bound Dog (MS Red)": "バウンド・ドック（MS形態・赤）",
	"Bound Dog (MA Red)": "バウンド・ドック（MA形態・赤）",
	"Bound Dog (MS Yellow)": "バウンド・ドック（MS形態・黄）",
	"Bound Dog (MA Yellow)": "バウンド・ドック（MA形態・黄）",
	"Bagi Doga": "バギ・ドーガ",
	"Bazam": "バーザム",
	"Bajimu": "バージム",
	"Batara": "バダラ",
	"Hardygun": "ハーディガン",
	"Patouria": "パトゥーリア",
	"Batorabensunmamu": "バトラーベンスンマム",
	"Perfect Gundam": "パーフェクトガンダム",
	"Perfect Ziong": "パーフェクト・ジオング",
	"Paburiku": "パブリク",
	"Pallas Athena": "パラス・アテネ",
	"Barient": "バリエント",
	"Harry's Custom Sumo": "ハリー専用スモー",
	"Harison's Custom Gundam F91": "ハリソン専用ガンダムF91",
	"Halo": "ハロ",
	"Powered GM": "パワードジム",
	"Burns's Custom Batara": "バーンズ専用バタラ",
	"Bandit": "バンディット",
	"Hanburabi": "ハンブラビ",
	"Hanma Hanma": "ハンマ・ハンマ",
	"Vigna Zera": "ビギナ・ゼラ",
	"Vigna Gina": "ビギナ・ギナ",
	"Bigzam": "ビグザム",
	"Biguro": "ビグロ",
	"Biguro Maiyer": "ビグロマイヤー",
	"B3 Gouf": "B3グフ",
	"Hiphebi": "ヒップヘビー",
	"133 type Ball": "133式ボール",
	"Hyaku Shiki": "百式",
	"Hyaku Shiki Kai": "百式改",
	"Birugenau": "ビルナケウ",
	"Virgo": "ビルゴ",
	"Virgo II": "ビルゴII",
	"Virgo III": "ビルゴIII",
	"FAZZ": "FAZZ",
	"Fantoma": "ファントマ",
	"Fan Fan": "ファンファン",
	"Phoenix Gundam": "フェニックスガンダム",
	"Feburaru": "フェブラル",
	"Bushi": "ブッシ",
	"Fly Mantha": "フライ・マンタ",
	"Burao Buro": "ブラウ・ブロ",
	"Flat": "フラット",
	"Flat Kai (Militia)": "フラット改（ミリシャ）",
	"Britova": "ブリトヴァ",
	"Flint": "フリント",
	"FA Gundam": "FAガンダム",
	"FA Gundam Mk II": "FAガンダムMKII",
	"FA Gundam Mk III": "FAガンダムMKIII",
	"FA Hyaku Shiki Kai": "FA百式改",
	"Burugengu": "ブルッケング",
	"Burugengu (Leader type)": "ブルッケング（指揮官機）",
	"Blue Destiny 1": "ブルーディスティニー1号機",
	"Blue Destiny 2": "ブルーディスティニー2号機",
	"Blue Destiny 2 (Red)": "ブルーディスティニー2号機（赤）",
	"Blue Destiny 3": "ブルーディスティニー3号機",
	"Buruwan": "ブルワン",
	"Proto Z Gundam": "プロトZガンダム",
	"Prototype Gundam": "プロトタイプガンダム",
	"Prototype Qubeley": "プロトタイプ・キュベレイ",
	"Prototype Psyco Gundam": "プロトタイプサイコガンダム",
	"Prototype ZZ Gundam": "プロトタイZZガンダム",
	"Prototype Rick Dias": "プロトタイプリックディアス",
	"Proba": "プローバー",
	"Besukatore": "ペスカトーレ",
	"Pez Batara": "ペズ・バタラ",
	"Pezun Dowaji": "ペズン・ドワッジ",
	"Penelope": "ペーネロペー",
	"Heavy Gun": "ヘビーガン",
	"Heavy Gun (Macedonia)": "ヘビーガン（マケドニア仕様）",
	"Heavy Gundam": "ヘビーガンダム",
	"Belga Giros": "ベルガ・ギロス",
	"Belga Giros (Black)": "ベルガ・ギロス（黒）",
	"Belga Daras": "ベルガ・ダラス",
	"Belga Barus": "ベルガ・バルス",
	"Beltigo": "ベルティゴ",
	"Hover Truck": "ホバートラック",
	"Hobihito": "ホバーヒート",
	"Hobi Hizaku": "ホバーハイザック",
	"Polar Bear": "ポーラベアー",
	"Borinook Samaan": "ボリノーク・サマーン",
	"Ball": "ボール",
	"Ball Kai": "ボール改修型",
	"Bolshanon": "ボルジャーノン",
	"Bolt Gundam": "ボルトガンダム",
	"Maguanarc": "マグアナック",
	"Auda's Custom Maguanarc": "アウダ専用マグアナック",
	"Abdul's Custom Maguanarc": "アブドル専用マグアナック",
	"Ahmad's Custom Maguanarc": "アフマド専用マグアナック",
	"Lacid's Custom Maguanarc": "ラシード専用マグアナック",
	"Ma Kube's Custom Gouf": "マ・クベ専用グフ",
	"Master Gundam": "マスターガンダム",
	"Mazera Attack": "マゼラ・アタック",
	"Matsunaga's Custom High Mobility Zaku II": "アツナガ専用高機動型ザクII",
	"Matsunaga's Custom Zaku II": "マツナガ専用ザクII",
	"Mahiro": "マヒロー",
	"Mermaid Gundam": "マーメイドガンダム",
	"Marasai": "マラサイ",
	"Mandala Gundam": "マンダラガンダム",
	"Musha Turn A Gundam": "武者ターンエーガンダム",
	"Muttou": "ムットゥー",
	"Mega Rider": "メガライダー",
	"Metasu": "メタス",
	"Metasu Kai": "メタス改",
	"Messa": "メッサー",
	"Messara": "メッサーラ",
	"Memedoza": "メッメドーサ",
	"Mercurius": "メリクリウス",
	"Mercurius Shuivan": "メリクリウス・シュイヴァン",
	"Jagd Doga": "ヤクト・ドーガ",
	"Jagd Doga (Gyunei type)": "ヤクト・ドーガ（ギュネイ専用機）",
	"Jagd Doga (Quess type)": "ヤクト・ドーガ（クェス専用機）",
	"Rising Gundam": "ライジングガンダム",
	"Raideen's Custom High Mobility Gelgog": "ライデン専用高機動型ゲルググ",
	"Raideen's Custom High Mobility Zaku II": "ライデン専用高機動型ザクII",
	"Rainosaras": "ライノサラス",
	"Rainosaras (A type)": "ライノサラス（A型）",
	"Rainosaras (B type)": "ライノサラス（B型）",
	"Rasuvet": "ラスヴェート",
	"Rasuvet (G-Bit)": "ラスヴェート（G-BIT）",
	"Lafressia": "ラフレシア",
	"Ral's Custom Zaku I": "ラル専用ザクI",
	"Lancelot's Custom Kurauda": "ランスロー専用クラウダ",
	"Lumber Gundam": "ランバーガンダム",
	"Leo": "リーオー",
	"Leo (Land use)": "リーオー（陸上用）",
	"Leo (Space use)": "リーオー（宇宙用）",
	"Leo (OZ)": "リーオー（OZ仕様）",
	"ReGZ": "リ・ガズィ（MS形態）",
	"ReGZ (BWS)": "リ・ガズィ（B・W・S装備）",
	"ReGZ Custom": "リ・ガズィ・カスタム",
	"Rigaru": "リカール",
	"Rig Contioh": "リグ・コンティオ",
	"Rig Shacko": "リグ・シャッコー",
	"Rig Shacko (Another use)": "リグ・シャッコー（近衛師団用）",
	"Land use Gundam": "陸戦型ガンダム",
	"Land use GM": "陸戦型ジム",
	"Land use Hyaku Shiki Kai": "陸戦型百式改",
	"Rig Ring": "リグ・リング",
	"Rigerugu": "リゲルグ",
	"Rick Dias": "リック・ディアス",
	"Rick Dias (Red)": "リック・ディアス（赤）",
	"Rick Dias (Black)": "リック・ディアス（黒）",
	"Rick Dias II": "リック・ディアスII",
	"Rick Dom": "リック・ドム",
	"Rick Dom II": "リック・ドムII",
	"RF Azam": "RFアッザム",
	"RF Gyan": "RFギャン",
	"RF Gouf": "RFグフ",
	"RF Gelgog": "RFゲルググ",
	"RF Gelgog (Leader type)": "RFゲルググ（指揮官機）",
	"RF Zaku": "RFザク",
	"RF Zaku (Leader type)": "RFザク（指揮官機）",
	"RF Zugok": "RFズゴック",
	"RF Desert Dom": "RFデザート・ドム",
	"RF Dom": "RFドム",
	"Mass Product Gun Cannon": "量産型ガンキャノン",
	"Mass Product Gun Cannon (Grey)": "量産型ガンキャノン（灰）",
	"Mass Product Guntank": "量産型ガンタンク",
	"Mass Product Qubeley": "量産型キュベレイ",
	"Mass Product Guabaze": "量産型クァバーゼ",
	"Mass Product Psyco Gundam": "量産型サイコガンダム",
	"Mass Product Z Gundam": "量産型Zガンダム",
	"Mass Product ZZ Gundam": "量産型ZZガンダム",
	"Mass Product Nu Gundam": "量産型ニューガンダム",
	"Mass Product Hanma Hanma": "量産型ハンマ・ハンマ",
	"Mass Product Bigzam": "量産型ビグザム",
	"Mass Product Hyaku Shiki Kai": "量産型百式改",
	"Rugen": "ルッグン",
	"Leosu": "レオス",
	"Leoru": "レオール",
	"Leon": "レオン",
	"Rezun's Custom Gira Doga": "レズン専用ギラ・ドーガ",
	"61 Tank": "61式戦車",
	"Waiban": "ワイバーン",
	"Unknown MS": "謎の機体",
};